model:
  num_classes: 64
  model_path: models/model.pth

dataset:
  dataset_path: data/Stanford_Dogs_256
  csv_path: data/dataset_small_info.csv
  batch_size: 32
  image_size: [256,256]

train:
  num_epochs: 1
  learning_rate: 1e-3
  use_fp16: True
  export_onnx: 'models/model.onnx'
  experiment_name: stanforddogs_resnet18
  run_name: run_1


infer:
  csv_output_save_path: data/model_output.csv
  accuracy_topk: [1,3,5]
