dataset:
  dataset_path: data/Stanford_Dogs_256
  csv_path: data/dataset_info.csv
  batch_size: 32

train:
  num_epochs: 5
  learning_rate: 1e-3
  model_save_path: models/model.pth
  experiment_name: exp_1
  run_name: stanforddogs_resnet18
  tracking_uri: <tracking_uri>
  registry_uri: <registry_uri>

infer:
  model_load_path: models/model.pth
  csv_output_save_path: data/model_output.csv
  accuracy_topk: [1,3,5]
